### ISSUE TITLE
-n option causes metrics-docker-stats.rb to fail

### ISSUE THREAD

**Issue by soichih** [sensu-plugins/sensu-plugins-docker#16]
I can run metrics-docker-stats.rb successfully by doing following

```
 /opt/sensu/embedded/bin/ruby ./metrics-docker-stats.rb -H /var/run/docker.sock -p unix 
```

However, when I add "-n" option, it fails with following message.

```
...
soichi7.ppa.iu.edu.docker.portal-apache1.memory_stats.stats.total_unevictable 0 1449347656
soichi7.ppa.iu.edu.docker.portal-apache1.memory_stats.stats.unevictable 0 1449347656
soichi7.ppa.iu.edu.docker.portal-apache1.memory_stats.failcnt 0 1449347656
soichi7.ppa.iu.edu.docker.portal-apache1.memory_stats.limit 12431413248 1449347656
Check failed to run: 757: unexpected token at 'no such id: portal-apache1mysql
', ["/opt/sensu/embedded/lib/ruby/2.0.0/json/common.rb:155:in `parse'", "/opt/sensu/embedded/lib/ruby/2.0.0/json/common.rb:155:in `parse'", "./metrics-docker-stats.rb:113:in `block (3 levels) in docker_api'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/protocol.rb:411:in `call_block'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/protocol.rb:402:in `<<'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/protocol.rb:106:in `read'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http/response.rb:284:in `block in read_body_0'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http/response.rb:269:in `inflater'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http/response.rb:274:in `read_body_0'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http/response.rb:201:in `read_body'", "./metrics-docker-stats.rb:112:in `block (2 levels) in docker_api'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:1419:in `block (2 levels) in transport_request'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http/response.rb:162:in `reading_body'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:1418:in `block in transport_request'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:1409:in `catch'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:1409:in `transport_request'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:1382:in `request'", "./metrics-docker-stats.rb:111:in `block in docker_api'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:852:in `start'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:582:in `start'", "./metrics-docker-stats.rb:109:in `docker_api'", "./metrics-docker-stats.rb:158:in `container_stats'", "./metrics-docker-stats.rb:91:in `block in run'", "./metrics-docker-stats.rb:90:in `each'", "./metrics-docker-stats.rb:90:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]
```

**Comment by analytically** [comment]
What docker image were you runnning?

**Comment by soichih** [comment]
@analytically I have various docker container running on this host (about 20 or so).

**Comment by eheydrick** [comment]
Is this still an issue for you?

**Comment by eheydrick** [comment]
Maybe caused by https://github.com/sensu-plugins/sensu-plugins-docker/issues/18?

**Comment by soichih** [comment]
Yes, this is still an issue.

```
# /opt/sensu/embedded/bin/gem update sensu-plugins-docker
Updating installed gems
Nothing to update
# ./metrics-docker-stats.rb -H /var/run/docker.sock -p unix -n redis
core-test1.sca.iu.edu.docker.mongodb-sca1.precpu_stats.cpu_usage.total_usage 0 1464123856
core-test1.sca.iu.edu.docker.mongodb-sca1.precpu_stats.cpu_usage.percpu_usage
core-test1.sca.iu.edu.docker.mongodb-sca1.precpu_stats.cpu_usage.usage_in_kernelmode 0 1464123856
core-test1.sca.iu.edu.docker.mongodb-sca1.precpu_stats.cpu_usage.usage_in_usermode 0 1464123856
...
core-test1.sca.iu.edu.docker.gocdb2sls-test.networks.eth0.tx_bytes 417402032 1464123856
core-test1.sca.iu.edu.docker.gocdb2sls-test.networks.eth0.tx_packets 3502816 1464123856
core-test1.sca.iu.edu.docker.gocdb2sls-test.networks.eth0.tx_errors 0 1464123856
core-test1.sca.iu.edu.docker.gocdb2sls-test.networks.eth0.tx_dropped 0 1464123856
Check failed to run: 757: unexpected token at 'no such id: gocdb2sls-testsls
', ["/opt/sensu/embedded/lib/ruby/2.0.0/json/common.rb:155:in `parse'", "/opt/sensu/embedded/lib/ruby/2.0.0/json/common.rb:155:in `parse'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugins-docker-1.0.0/bin/metrics-docker-stats.rb:113:in `block (3 levels) in docker_api'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/protocol.rb:411:in `call_block'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/protocol.rb:402:in `<<'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/protocol.rb:106:in `read'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http/response.rb:284:in `block in read_body_0'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http/response.rb:269:in `inflater'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http/response.rb:274:in `read_body_0'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http/response.rb:201:in `read_body'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugins-docker-1.0.0/bin/metrics-docker-stats.rb:112:in `block (2 levels) in docker_api'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:1419:in `block (2 levels) in transport_request'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http/response.rb:162:in `reading_body'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:1418:in `block in transport_request'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:1409:in `catch'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:1409:in `transport_request'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:1382:in `request'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugins-docker-1.0.0/bin/metrics-docker-stats.rb:111:in `block in docker_api'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:852:in `start'", "/opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:582:in `start'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugins-docker-1.0.0/bin/metrics-docker-stats.rb:109:in `docker_api'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugins-docker-1.0.0/bin/metrics-docker-stats.rb:158:in `container_stats'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugins-docker-1.0.0/bin/metrics-docker-stats.rb:91:in `block in run'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugins-docker-1.0.0/bin/metrics-docker-stats.rb:90:in `each'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugins-docker-1.0.0/bin/metrics-docker-stats.rb:90:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]

```

**Comment by eheydrick** [comment]
@soichih can you try the latest release. If it's still a problem can you post the output from the stats endpoint:  `curl -q --unix-socket /var/run/docker.sock http:/containers/$container_name/stats?stream=false` where `$container_name` is the name of the container it's tripping on.

**Comment by majormoses** [comment]
closing due to inactivity, comment back and I will re-open it if you plan on working on helping with re-producing this.

**Comment by gdhgdhgdh** [comment]
I think I'm being affected by the same thing. I'm using Docker 17.09.1-ce (API 1.32), and `sensu-plugins-docker` 3.0.0

If I run `metrics-docker-stats.rb` I get a block of stats for each running container. When I add `-n` to the commandline, the first container's stats are printed OK (with the nice-name) but then the script bombs out with 

```
dev-dockerhost-devperformance-i0f02367b0688c91b6.docker.devperformance_cdsRisk_1.networks.eth0.tx_dropped 0 1519221799
Check failed to run: 404 "Not Found", ["/opt/sensu/embedded/lib/ruby/2.3.0/net/http/response.rb:120:in `error!'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-docker-3.0.0/lib/sensu-plugins-docker/client_helpers.rb:41:in `call'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-docker-3.0.0/bin/metrics-docker-stats.rb:175:in `container_stats'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-docker-3.0.0/bin/metrics-docker-stats.rb:122:in `block in run'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-docker-3.0.0/bin/metrics-docker-stats.rb:121:in `each'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-docker-3.0.0/bin/metrics-docker-stats.rb:121:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-2.4.0/lib/sensu-plugin/cli.rb:57:in `block in <class:CLI>'"]
```

I `strace`d the script, and can see that it's bundling a number of the container names together:

```
[pid  1413] write(1, "dev-dockerhost-devperformance-i0f02367b0688c91b6.docker.devperformance_cdsRisk_1.networks.eth0.tx_dropped 0 1519222140", 118dev-dockerhost-devperformance-i0f02367b0688c91b6.docker.devperformance_cdsRisk_1.networks.eth0.tx_dropped 0 1519222140) = 118
[pid  1413] write(1, "\n", 1
)           = 1
[pid  1413] write(7, "GET /containers/devperformance_riskTestHarness_1devperformance_riskingServiceJava_1/stats?stream=0 HTTP/1.1\r\nAccept-Encoding: gz"..., 217) = 217
[pid  1413] write(1, "Check failed to run: 404 \"Not Found\", [\"/opt/sensu/embedded/lib/ruby/2.3.0/net/http/response.rb:120:in `error!'\", \"/opt/sensu/em"..., 850Check failed to run: 404 "Not Found", ["/opt/sensu/embedded/lib/ruby/2.3.0/net/http/response.rb:120:in `error!'"
[...]
```

**Comment by majormoses** [comment]
@gdhgdhgdh does upgrading your docker to a newer version help? reading [here](https://github.com/sensu-plugins/sensu-plugins-docker#functionality) this plugin currently supports `>= 1.18`

**Comment by gdhgdhgdh** [comment]
Hey - there was never a docker version `1.18`. After 1.13, Docker moved to 'YEAR.MONTH' versioning similar to Ubunto.

That `1.18` version number surely refers to the `docker-engine` API. v `1.18` was released quite a long time ago, and I'm using the community edition of Docker 17.09.1 ... this is bundled with `1.32` of the `docker-engine API`

**Comment by majormoses** [comment]
this is what happens when things change and I am not really on top of the changes going on there.

Can you post the output that was requested here https://github.com/sensu-plugins/sensu-plugins-docker/issues/16#issuecomment-225217361

**Comment by gdhgdhgdh** [comment]
:+1:

```
[root@dev-dockerhost-devperformance-i0f02367b0688c91b6 ~]# curl -q --unix-socket /var/run/docker.sock http:/containers/devperformance_cdsRisk_1/stats?stream=false{"read":"2018-02-22T08:02:34.902888422Z","preread":"2018-02-22T08:02:33.903546511Z","pids_stats":{"current":32},"blkio_stats":{"io_service_bytes_recursive":[{"major":202,"minor":16,"op":"Read","value":4608},{"major":202,"minor":16,"op":"Write","value":0},{"major":202,"minor":16,"op":"Sync","value":0},{"major":202,"minor":16,"op":"Async","value":4608},{"major":202,"minor":16,"op":"Total","value":4608},{"major":253,"minor":2,"op":"Read","value":4608},{"major":253,"minor":2,"op":"Write","value":0},{"major":253,"minor":2,"op":"Sync","value":0},{"major":253,"minor":2,"op":"Async","value":4608},{"major":253,"minor":2,"op":"Total","value":4608},{"major":253,"minor":3,"op":"Read","value":4608},{"major":253,"minor":3,"op":"Write","value":0},{"major":253,"minor":3,"op":"Sync","value":0},{"major":253,"minor":3,"op":"Async","value":4608},{"major":253,"minor":3,"op":"Total","value":4608},{"major":253,"minor":19,"op":"Read","value":110598656},{"major":253,"minor":19,"op":"Write","value":0},{"major":253,"minor":19,"op":"Sync","value":0},{"major":253,"minor":19,"op":"Async","value":110598656},{"major":253,"minor":19,"op":"Total","value":110598656}],"io_serviced_recursive":[{"major":202,"minor":16,"op":"Read","value":2},{"major":202,"minor":16,"op":"Write","value":0},{"major":202,"minor":16,"op":"Sync","value":0},{"major":202,"minor":16,"op":"Async","value":2},{"major":202,"minor":16,"op":"Total","value":2},{"major":253,"minor":2,"op":"Read","value":2},{"major":253,"minor":2,"op":"Write","value":0},{"major":253,"minor":2,"op":"Sync","value":0},{"major":253,"minor":2,"op":"Async","value":2},{"major":253,"minor":2,"op":"Total","value":2},{"major":253,"minor":3,"op":"Read","value":2},{"major":253,"minor":3,"op":"Write","value":0},{"major":253,"minor":3,"op":"Sync","value":0},{"major":253,"minor":3,"op":"Async","value":2},{"major":253,"minor":3,"op":"Total","value":2},{"major":253,"minor":19,"op":"Read","value":2659},{"major":253,"minor":19,"op":"Write","value":0},{"major":253,"minor":19,"op":"Sync","value":0},{"major":253,"minor":19,"op":"Async","value":2659},{"major":253,"minor":19,"op":"Total","value":2659}],"io_queue_recursive":[],"io_service_time_recursive":[],"io_wait_time_recursive":[],"io_merged_recursive":[],"io_time_recursive":[],"sectors_recursive":[]},"num_procs":0,"storage_stats":{},"cpu_stats":{"cpu_usage":{"total_usage":83429312654,"percpu_usage":[15653692742,17526714543,11345046936,11559620447,6673075965,10660298325,3417656126,6593207570],"usage_in_kernelmode":2260000000,"usage_in_usermode":37980000000},"system_cpu_usage":10963257570000000,"online_cpus":8,"throttling_data":{"periods":0,"throttled_periods":0,"throttled_time":0}},"precpu_stats":{"cpu_usage":{"total_usage":83428324908,"percpu_usage":[15653589331,17526685670,11344975147,11559481651,6673043701,10659704667,3417656126,6593188615],"usage_in_kernelmode":2260000000,"usage_in_usermode":37980000000},"system_cpu_usage":10963249650000000,"online_cpus":8,"throttling_data":{"periods":0,"throttled_periods":0,"throttled_time":0}},"memory_stats":{"usage":1011503104,"max_usage":1013018624,"stats":{"active_anon":901468160,"active_file":20209664,"cache":110034944,"hierarchical_memory_limit":9223372036854771712,"hierarchical_memsw_limit":9223372036854771712,"inactive_anon":0,"inactive_file":89825280,"mapped_file":14041088,"pgfault":116643,"pgmajfault":25,"pgpgin":136323,"pgpgout":98373,"rss":901468160,"rss_huge":857735168,"swap":0,"total_active_anon":901468160,"total_active_file":20209664,"total_cache":110034944,"total_inactive_anon":0,"total_inactive_file":89825280,"total_mapped_file":14041088,"total_pgfault":116643,"total_pgmajfault":25,"total_pgpgin":136323,"total_pgpgout":98373,"total_rss":901468160,"total_rss_huge":857735168,"total_swap":0,"total_unevictable":0,"unevictable":0},"limit":62069710848},"name":"/devperformance_cdsRisk_1","id":"941c262df733ff2b9eabe1931a79a4dcb2537832988a944c44c1910cb3843579","networks":{"eth0":{"rx_bytes":4575,"rx_packets":88,"rx_errors":0,"rx_dropped":0,"tx_bytes":0,"tx_packets":0,"tx_errors":0,"tx_dropped":0}}}
```

**Comment by gdhgdhgdh** [comment]
That's interesting - the behaviour is slightly different this morning. Now it's able to show the stats for the first two containers before concatenating the names of containers 3 + 4 ...

```
[root@dev-dockerhost-devperformance-i0f02367b0688c91b6 ~]# strace -f -e write -s 128 /opt/sensu/embedded/bin/metrics-docker-stats.rb -n | grep write.7
strace: Process 11549 attached
strace: Process 11554 attached
[pid 11554] +++ exited with 0 +++
[pid 11548] write(7, "GET /containers/json HTTP/1.1\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nAccept: */*\r\nUser-Agent: Ruby\r\nHost: lo"..., 139) = 139
[pid 11548] write(7, "GET /containers/devperformance_cdsRisk_1/stats?stream=0 HTTP/1.1\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nAcce"..., 174) = 174
[pid 11548] write(7, "GET /containers/devperformance_riskingServiceJava_1/stats?stream=0 HTTP/1.1\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;"..., 185) = 185
[pid 11548] write(7, "GET /containers/devperformance_cdsRisk_1devperformance_publishService_1/stats?stream=0 HTTP/1.1\r\nAccept-Encoding: gzip;q=1.0,def"..., 205) = 205
[pid 11548] write(1, "\ndev-dockerhost-devperformance-i0f02367b0688c91b6.docker.devperformance_riskingServiceJava_1.networks.eth0.tx_packets 62562 1519"..., 1245) = 1245
[pid 11549] +++ exited with 0 +++
+++ exited with 3 +++

```

**Comment by sestary** [comment]
The container name concatenating happens when containers are linked together. These links are represented in the json in the "name" field as the origin container name / the linked container. The / is then stripped out by the code and you end up with a concatenated name.

The correct name isn't always returned as the first item in the list processing here: 
https://github.com/sensu-plugins/sensu-plugins-docker/blob/98b341859680027ee06f99093dc8d6ae85e56e13/bin/metrics-docker-stats.rb#L156

**Comment by theyough** [comment]
any update ?

**Comment by majormoses** [comment]
Ah that makes sense as `/` is not a valid character in a container name per the [source code](https://github.com/moby/moby/blob/8e610b2b55bfd1bfa9436ab110d311f5e8a74dcb/daemon/names/names.go#L5-L6) can we split and remove anything past the first `/`?
