### ISSUE TITLE
Are  API version:  1.23 supported?

### ISSUE THREAD

**Issue by rbucchi** [sensu-plugins/sensu-plugins-docker#46]
```
# docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64
```

```
Check failed to run: 419: unexpected token at '{"Id":"ac99cc9f8563142d82c9a2af00e98164372', ["/opt/sensu
/embedded/lib/ruby/2.3.0/json/common.rb:156:in `parse'", "/opt/sensu/embedded/lib/ruby/2.3.0/json/common
.rb:156:in `parse'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-docker-1.1.3/bin/metric
s-docker-stats.rb:121:in `block (3 levels) in docker_api'", "/opt/sensu/embedded/lib/ruby/2.3.0/net/prot
ocol.rb:411:in `call_block'", "/opt/sensu/embedded/lib/ruby/2.3.0/net/protocol.rb:402:in `<<'", "/opt/se
nsu/embedded/lib/ruby/2.3.0/net/protocol.rb:104:in `read'", "/opt/sensu/embedded/lib/ruby/2.3.0/net/http
/response.rb:319:in `read_chunked'", "/opt/sensu/embedded/lib/ruby/2.3.0/net/http/response.rb:283:in `bl
ock in read_body_0'", "/opt/sensu/embedded/lib/ruby/2.3.0/net/http/response.rb:276:in `inflater'", "/opt
/sensu/embedded/lib/ruby/2.3.0/net/http/response.rb:281:in `read_body_0'", "/opt/sensu/embedded/lib/ruby
/2.3.0/net/http/response.rb:202:in `read_body'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plu
gins-docker-1.1.3/bin/metrics-docker-stats.rb:120:in `block (2 levels) in docker_api'", "/opt/sensu/embe
dded/lib/ruby/2.3.0/net/http.rb:1446:in `block in transport_request'", "/opt/sensu/embedded/lib/ruby/2.3
.0/net/http/response.rb:163:in `reading_body'", "/opt/sensu/embedded/lib/ruby/2.3.0/net/http.rb:1445:in 
`transport_request'", "/opt/sensu/embedded/lib/ruby/2.3.0/net/http.rb:1407:in `request'", "/opt/sensu/em
bedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-docker-1.1.3/bin/metrics-docker-stats.rb:119:in `block in 
docker_api'", "/opt/sensu/embedded/lib/ruby/2.3.0/net/http.rb:853:in `start'", "/opt/sensu/embedded/lib/
ruby/2.3.0/net/http.rb:584:in `start'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-dock
er-1.1.3/bin/metrics-docker-stats.rb:117:in `docker_api'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems
/sensu-plugins-docker-1.1.3/bin/metrics-docker-stats.rb:152:in `list_containers'", "/opt/sensu/embedded/
lib/ruby/gems/2.3.0/gems/sensu-plugins-docker-1.1.3/bin/metrics-docker-stats.rb:96:in `run'", "/opt/sens
u/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CL
I>'"]
```

**Comment by majormoses** [comment]
related or duplicate: https://github.com/sensu-plugins/sensu-plugins-docker/issues/45

**Comment by majormoses** [comment]
@rbucchi can you verify if its the same issue?

**Comment by rbucchi** [comment]
@majormoses sorry, I actually cannot anymore

**Comment by majormoses** [comment]
ok I am going to close this in favor of #45 then if someone hits this and feels it's different just comment here and I will re-open.
